AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda functions for Mailing List, Book Info, and Welcome Modal

Parameters:
  DbName:
    Type: String
    Description: Database name
  DbUser:
    Type: String
    Description: Database username
  DbPassword:
    Type: String
    Description: Database password
  DbHost:
    Type: String
    Description: Database host
  DbPort:
    Type: String
    Description: Database port
  GoogleBooksApiKey:
    Type: String
    Description: "API key for Google Books API"
  OpenAIApiKey:
    Type: String
    Description: "API key for OpenAI"

Resources:
  MailingListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Environment:
        Variables:
          DB_NAME: !Ref DbName
          DB_USER: !Ref DbUser
          DB_PASSWORD: !Ref DbPassword
          DB_HOST: !Ref DbHost
          DB_PORT: !Ref DbPort
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /subscribe
            Method: post

  GetBookInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get_book_info.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Environment:
        Variables:
          DB_NAME: !Ref DbName
          DB_USER: !Ref DbUser
          DB_PASSWORD: !Ref DbPassword
          DB_HOST: !Ref DbHost
          DB_PORT: !Ref DbPort
      Events:
        GetBookEvent:
          Type: Api
          Properties:
            Path: /getBook
            Method: get

  GetUpcomingEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get_upcoming_events.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Environment:
        Variables:
          DB_NAME: !Ref DbName
          DB_USER: !Ref DbUser
          DB_PASSWORD: !Ref DbPassword
          DB_HOST: !Ref DbHost
          DB_PORT: !Ref DbPort
      Events:
        GetUpcomingEventsApi:
          Type: Api
          Properties:
            Path: /getUpcomingEvents
            Method: get

  GetBooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get_google_books.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Timeout: 10
      Environment:
        Variables:
          API_KEY: !Ref GoogleBooksApiKey
          DB_NAME: !Ref DbName
          DB_USER: !Ref DbUser
          DB_PASSWORD: !Ref DbPassword
          DB_HOST: !Ref DbHost
          DB_PORT: !Ref DbPort
      Events:
        GetBooksApi:
          Type: Api
          Properties:
            Path: /getBooks
            Method: get

  WelcomeModalFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: welcome_page_count.lambda_handler
      Runtime: python3.9
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          DB_NAME: !Ref DbName
          DB_USER: !Ref DbUser
          DB_PASSWORD: !Ref DbPassword
          DB_HOST: !Ref DbHost
          DB_PORT: !Ref DbPort
      Events:
        WelcomeModalApi:
          Type: Api
          Properties:
            Path: /welcome
            Method: post

  QuizFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: quiz_response.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Timeout: 30
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIApiKey
      Events:
        QuizApi:
          Type: Api
          Properties:
            Path: /quiz
            Method: post

Outputs:
  MailingListApi:
    Description: "API Gateway endpoint URL for Prod stage for Mailing List function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/subscribe/"

  GetBookInfoApi:
    Description: "API Gateway endpoint URL for Prod stage for Get Book Info function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getBook/"

  GetUpcomingEventsApi:
    Description: "API Gateway endpoint URL for Prod stage for Get Upcoming Events function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getUpcomingEvents/"

  GetBooksApi:
    Description: "API Gateway endpoint URL for Prod stage for Get Books function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getBooks/"

  WelcomeModalApi:
    Description: "API Gateway endpoint URL for Prod stage for Welcome Modal function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/welcome/"

  QuizApi:
    Description: "API Gateway endpoint URL for Prod stage for Quiz function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/quiz/"